CREATE TABLE `students` (
`id` INT NOT NULL AUTO_INCREMENT,
`name` VARCHAR(20) NOT NULL,
`entYear` INT NOT NULL,
`major` INT NOT NULL,
`personalNum` INT NOT NULL,
`phoneNum` VARCHAR(11) NOT NULL,
`address` VARCHAR(50) NOT NULL, 
`creditSum` INT NOT NULL DEFAULT 0,
`creditAverage` DOUBLE NOT NULL DEFAULT 0.0,
`is_attending` TINYINT(1) NOT NULL DEFAULT 1,
PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;